# Generated by Django 6.0.5 on 2026-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='recorrencia',
            field=models.CharField(choices=[('nao_repete', 'Não se repete (Única)'), ('diaria', 'Todos os dias'), ('semanal', 'Toda semana'), ('mensal', 'Todo mês')], default='nao_repete', max_length=20),
        ),
    ]
