# Generated by Django 6.0.5 on 2026-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_recorrencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
