# Generated by Django 6.0.5 on 2026-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_remove_tarefa_tipo_alter_tarefa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
